exclude: '^go.sum'
default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: mixed-line-ending
        args: ["--fix=no"]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.21.2
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        args:
          - "--skip=\"go.sum\""
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.2.0
    hooks:
      - id: detect-secrets
  - repo: https://github.com/yoheimuta/protolint
    rev: v0.37.1
    hooks:
      - id: protolint
  - repo: https://github.com/hadolint/hadolint
    rev: v2.9.3
    hooks:
      - id: hadolint
  - repo: https://github.com/barklan/git-hooks
    rev: v0.0.17
    hooks:
      - id: go-test
      - id: forbid-binary
  - repo: local
    hooks:
      - id: golang-filenames
        name: check go filenames
        entry: go filenames must be snake-case
        language: fail
        files: '[a-z0-9_/]*[^a-z0-9_/]+[a-z0-9_]*\.go$'
      - id: dotenv-linter
        name: run dotenv linter
        language: docker_image
        entry: dotenvlinter/dotenv-linter --recursive
        files: \.env$
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ""
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: weekly
  skip: []
  submodules: false
