version: "3.9"

services:
  myapp:
    image: '${DOCKER_IMAGE_PREFIX?Variable not set}myapp:rolling'
    build:
      context: .
      dockerfile: dockerfiles/myapp.dockerfile
      args:
        DOCKER_IMAGE_PREFIX: ${DOCKER_IMAGE_PREFIX?Variable not set}
        BUILDKIT_INLINE_CACHE: 1
    volumes:
      - myapp-data:/data
    networks:
      - traefik-public
    env_file:
      - ./.env

networks:
  traefik-public:
    external: true

volumes:
  myapp-data:
