// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/barklan/gotemplate/pkg/caching"
	"github.com/barklan/gotemplate/pkg/db"
	"github.com/barklan/gotemplate/pkg/logging"
	"github.com/barklan/gotemplate/pkg/myapp/config"
	"github.com/barklan/gotemplate/pkg/myapp/rest"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func InitApp() (*rest.PublicCtrl, error) {
	logger := logging.NewAuto()
	configConfig, err := config.Read()
	if err != nil {
		return nil, err
	}
	pool, err := db.Conn(logger)
	if err != nil {
		return nil, err
	}
	fastCache, err := caching.NewArc(configConfig)
	if err != nil {
		return nil, err
	}
	publicCtrl := rest.NewCtrl(logger, configConfig, pool, fastCache)
	return publicCtrl, nil
}
